export const GOAL_RULES = {
  MAX_GOALS_PER_CYCLE: 8,
  MIN_WEIGHTAGE: 10,
  MAX_WEIGHTAGE: 50,
  TOTAL_WEIGHTAGE: 100,
  MIN_GOALS_TO_SUBMIT: 2,
  CATEGORY_WEIGHTAGE_MIN: { STRATEGIC: 30 },
} as const;
