#!/usr/bin/env node
/**
 * Generates backend/.env and frontend/.env.local with safe local defaults.
 * Run: node scripts/setup-env.mjs
 */
import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const backendEnvPath = join(root, 'backend', '.env');
const frontendEnvPath = join(root, 'frontend', '.env.local');

function secret() {
  return randomBytes(48).toString('base64url');
}

function parseEnv(content) {
  const map = {};
  for (const line of content.split('\n')) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const i = t.indexOf('=');
    if (i === -1) continue;
    map[t.slice(0, i).trim()] = t.slice(i + 1).trim();
  }
  return map;
}

function loadExisting(path) {
  if (!existsSync(path)) return {};
  return parseEnv(readFileSync(path, 'utf8'));
}

function keepOr(existing, key, fallback) {
  const v = existing[key];
  if (v && !v.includes('change-me') && !v.includes('replace-me') && v !== 'dummy-client-id-replace-me') {
    return v;
  }
  return fallback;
}

const existingBackend = loadExisting(backendEnvPath);
const existingFrontend = loadExisting(frontendEnvPath);

const jwtSecret = keepOr(existingBackend, 'JWT_SECRET', secret());
const jwtRefresh = keepOr(existingBackend, 'JWT_REFRESH_SECRET', secret());

const backendEnv = `# Saarthi Backend — generated by scripts/setup-env.mjs
# Re-run: node scripts/setup-env.mjs (keeps your filled-in API keys)

# ── REQUIRED (auto-set) ─────────────────────────────────────
JWT_SECRET=${jwtSecret}
JWT_REFRESH_SECRET=${jwtRefresh}
NODE_ENV=development
PORT=3001
ALLOWED_ORIGINS=http://localhost:3000
FRONTEND_URL=http://localhost:3000

# Database: SQLite (no env needed). File: backend/prisma/dev.db
# Run once: npm run db:migrate && npm run db:seed

# ── EMAIL (optional — leave SMTP_HOST empty for console-only dev) ──
# HOW TO GET (Mailtrap — easiest for testing):
#   1. https://mailtrap.io → Sign up → Email Testing → Inboxes → SMTP Settings
#   2. Copy host, port, user, pass into SMTP_* below
# Gmail: Google Account → Security → 2FA → App passwords → generate for "Mail"
SMTP_HOST=${existingBackend.SMTP_HOST ?? ''}
SMTP_PORT=${existingBackend.SMTP_PORT ?? '587'}
SMTP_SECURE=${existingBackend.SMTP_SECURE ?? 'false'}
SMTP_USER=${existingBackend.SMTP_USER ?? ''}
SMTP_PASS=${existingBackend.SMTP_PASS ?? ''}
SMTP_FROM=${existingBackend.SMTP_FROM ?? 'Saarthi Platform <noreply@saarthi.app>'}

# ── MICROSOFT SSO (optional) ────────────────────────────────
# HOW TO GET: https://portal.azure.com → Microsoft Entra ID → App registrations → New
#   - Redirect URI (SPA): http://localhost:3000
#   - API permissions: User.Read, openid, profile, email
#   - Certificates & secrets → New client secret → AZURE_CLIENT_SECRET
#   - Overview → Application (client) ID → AZURE_CLIENT_ID + NEXT_PUBLIC_AZURE_CLIENT_ID
#   - Overview → Directory (tenant) ID → AZURE_TENANT_ID + NEXT_PUBLIC_AZURE_TENANT_ID
AZURE_CLIENT_ID=${existingBackend.AZURE_CLIENT_ID ?? ''}
AZURE_CLIENT_SECRET=${existingBackend.AZURE_CLIENT_SECRET ?? ''}
AZURE_TENANT_ID=${existingBackend.AZURE_TENANT_ID ?? ''}

# ── MICROSOFT TEAMS (optional) ────────────────────────────────
# HOW TO GET: Teams channel → ⋯ → Connectors → Incoming Webhook → Create → copy URL
TEAMS_WEBHOOK_URL=${existingBackend.TEAMS_WEBHOOK_URL ?? ''}

# ── OPENAI (optional — attrition / AI insights) ─────────────
# HOW TO GET: https://platform.openai.com/api-keys → Create secret key
OPENAI_API_KEY=${existingBackend.OPENAI_API_KEY ?? ''}

# ── OTHER ───────────────────────────────────────────────────
ESCALATION_SLA_HOURS=${existingBackend.ESCALATION_SLA_HOURS ?? '48'}
API_BASE_URL=${existingBackend.API_BASE_URL ?? 'http://localhost:3001/api/v1'}
`;

const frontendEnv = `# Saarthi Frontend — generated by scripts/setup-env.mjs

# ── REQUIRED (auto-set) ─────────────────────────────────────
NEXT_PUBLIC_API_URL=${keepOr(existingFrontend, 'NEXT_PUBLIC_API_URL', 'http://localhost:3001/api/v1')}
NEXT_PUBLIC_APP_URL=${keepOr(existingFrontend, 'NEXT_PUBLIC_APP_URL', 'http://localhost:3000')}
NEXT_PUBLIC_APP_NAME=${keepOr(existingFrontend, 'NEXT_PUBLIC_APP_NAME', 'Saarthi')}

# ── MICROSOFT SSO (optional — match backend Azure app) ─────
# Same AZURE_CLIENT_ID and AZURE_TENANT_ID as backend/.env
NEXT_PUBLIC_AZURE_CLIENT_ID=${keepOr(existingFrontend, 'NEXT_PUBLIC_AZURE_CLIENT_ID', '')}
NEXT_PUBLIC_AZURE_TENANT_ID=${keepOr(existingFrontend, 'NEXT_PUBLIC_AZURE_TENANT_ID', 'common')}
`;

mkdirSync(dirname(backendEnvPath), { recursive: true });
mkdirSync(dirname(frontendEnvPath), { recursive: true });
writeFileSync(backendEnvPath, backendEnv, 'utf8');
writeFileSync(frontendEnvPath, frontendEnv, 'utf8');

console.log('✓ Wrote backend/.env');
console.log('✓ Wrote frontend/.env.local');
console.log('');
console.log('Auto-configured: JWT secrets, ports, CORS, API URL');
console.log('Still empty (fill when you need the feature):');
console.log('  SMTP_*     → real email (or use Mailtrap for testing)');
console.log('  AZURE_*    → Sign in with Microsoft');
console.log('  TEAMS_*    → Teams approval cards');
console.log('  OPENAI_*   → AI / attrition features');
console.log('');
console.log('Next steps:');
console.log('  cd backend && npm run db:migrate && npm run db:seed && npm run dev');
console.log('  cd frontend && npm run dev');
